### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by JGeovani** [JaySardhara/Video-Editor#1]
Hello @JaySardhara ,
Where do I find the dependencies of this project, as FFmpeg4Android, Editor?

Thanks,

**Comment by JaySardhara** [comment]
Hi @JGeovani , 
This was the FFMPEG build I used as *.so in my project. I am not very sure if this library is still available(http://androidwarzone.blogspot.com/2011/12/ffmpeg4android.html). 

But even if its not available you can recompile FFMPEG by yourself else there are many more available pre-compiled. Change the dependencies accordingly if you are changing the library.

Thanks.
