### ISSUE TITLE
Please share with me two libraries

### ISSUE THREAD

**Issue by tieuphu9x** [JaySardhara/Video-Editor#5]
I need two libraries:
android.library.reference.1=..\\ffmpeg4android
android.library.reference.2=..\\Editor
Can you share it?

**Comment by JaySardhara** [comment]
Hi @tieuphu9x ,

The FFMPEG library which I used can be found [here](http://androidwarzone.blogspot.com/2011/12/ffmpeg4android.html)
This lib. is newer and updated for Android studio, so you would not be able to import directly and run. 

There is no other library used.

**Comment by tieuphu9x** [comment]
Thank you so much.

**Comment by tieuphu9x** [comment]
​Thank you so much.​


Trân trọng,
Nguyễn Việt Phú
---------------------------------------------------------
Học viện Công nghệ Bưu chính Viễn thông (PTIT)
Địa chỉ: Cụm 10 - Tân Lập - Đan Phượng - Hà Nội
Số điện thoại: 091.400.1605

2017-03-14 12:47 GMT+07:00 Jay Sardhara <notifications@github.com>:
