### ISSUE TITLE
Can not output file when create video from images

### ISSUE THREAD

**Issue by hoanhnv** [JaySardhara/Video-Editor#6]
Hi @JaySardhara ,
I have run your sample to create a video from images then i saw log is success as below
'/sdcard/videokit/in.mp4 from assets to SDCARD finished succesfully'

 but i dont see the file in.mp4 in SDCARD of device.

Pls support or sugguest me solution. Thanks

**Comment by JaySardhara** [comment]
Hi @hoanhnv, 
Based on the info., it seems the transcoding process did not run at all. Hence that indicates that either there is problem in FFMPEG lib. which is used in this library or there is some permission issue in your device. 

Still can you update more so as I can understand symptoms.

**Comment by hoanhnv** [comment]
Hi @JaySardhara , i already solve it,thanks u!
i also want add more effect when generate images to video(Create slide show from image)
could u give me a sample for it?

**Comment by JaySardhara** [comment]
Check [this](https://trac.ffmpeg.org/wiki/Slideshow) and [this link](http://stackoverflow.com/questions/24961127/ffmpeg-create-video-from-images).
